POST http://localhost:8081/SignUp 
Content-Type: application/json 

{
    "email":"vipuljain@yahoo.com",
    "username":"vipul123",
    "name":"vipul jain",
    "contactNumber":"1234567576",
    "password1":"4321",
    "password2":"4321"
}

###
GET http://localhost:8081/createTable 
Content-Type: application/json 

###
POST http://localhost:8081/SignIn 
Content-Type: application/json 

{
    "email":"radhesham@gmail.com",
    "password":"4321"
}

###
GET http://localhost:8081/profile/radhe123 
Content-Type: application/json 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJhZGhlMTIzIiwiaWF0IjoxNjg0OTEzMTc0fQ.oH4_8yD5zCUpXoXroofO32QejTPEON9FXczjzAOVRlM