name: Linting

on: [push, pull_request]

jobs:

  Linting:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Lint code with prettier
        run: npx prettier --write .
